language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mongodb
  - redis-server

# command to install dependencies
install:
  - pip install pymongo
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install 'tornado<5.0.0'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then travis_retry pip install 'tornado<5.0.0'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then travis_retry pip install 'tornado<5.0.0'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then travis_retry pip install 'tornado<6.0.0'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry pip install 'tornado>=6.0.0'; fi
  - pip install redis
  - pip install docopt
  - pip install codecov
  - pip install coverage
# command to run tests
script:
  - python setup.py install
  - coverage run -m tests.runtests
after_success:
  - coverage xml
  - codecov -t dd6dbd11-3b2b-4930-9b81-34c313c74c8f
